In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('esketit2.csv')

In [3]:
data.head()

,Engagements,NBA_Follower_Count,Created,Type,Description,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month,...,teamTagged,otherTagged,top3Tagged,bottom3Tagged,hashtags,hasHashtag,HashLevel,sqrEngagements,monthDateYear,postsInThatDay
0,502093,36984682,2019-05-22 03:30:51,Video,The @raptors bench trio of @sergeibaka @norman...,95,4,Wednesday,1,5,...,0,1,0,0,[],False,None,252097380649,2019-05-22,5
1,603380,36984682,2019-05-22 02:53:33,Video,@kyle_lowry7 pulls from deep for the @raptors ...,64,2,Wednesday,1,5,...,0,1,0,0,[],False,None,364067424400,2019-05-22,5
2,603380,36984682,2019-05-22 02:19:58,Video,@k_mid22 with some english on the @bucks dime!,46,2,Wednesday,1,5,...,0,1,0,0,[],False,None,364067424400,2019-05-22,5
3,725100,36984682,2019-05-22 02:02:41,Video,Kawhi punches it home with the left on TNT!,43,0,Wednesday,1,5,...,0,0,0,0,[],False,None,525770010000,2019-05-22,5
4,661446,36984682,2019-05-22 00:47:49,Video,@giannis_an34 goes baseline early to rock the ...,57,1,Wednesday,1,5,...,0,1,0,0,[],False,None,437510810916,2019-05-22,5