In [1]:
import pandas as pd
import datetime
import numpy as np
import sklearn as sk
import re

In [2]:
data = pd.read_csv('holdout_set.csv', encoding = "ISO-8859-1")

In [3]:
data.head()

,Engagements,Followers at Posting,Created,Type,Description
0,NaN,36984682,2019-05-22 00:31:55 EDT,Photo,The @raptors even up the Eastern Conference Fi...
1,NaN,36984682,2019-05-21 23:20:41 EDT,Photo,The @raptors even the Eastern Conference Final...
2,NaN,36984682,2019-05-21 21:18:51 EDT,Video,@sergeibaka keeps it alive for the @raptors! (...
3,NaN,36955156,2019-05-21 18:20:09 EDT,Video,???? The SUPERHUMAN HANDS of Giannis & Kawhi ?...
4,NaN,36955156,2019-05-21 15:04:31 EDT,Video,?? the @raptors & @bucks in transition! #NBABr...

In [4]:
data['Len_Desc'] = data['Description'].str.len()

In [5]:
data['Tagged_Count'] = data['Description'].str.count('@')

In [6]:
data.head()

,Engagements,Followers at Posting,Created,Type,Description,Len_Desc,Tagged_Count
0,NaN,36984682,2019-05-22 00:31:55 EDT,Photo,The @raptors even up the Eastern Conference Fi...,55,1
1,NaN,36984682,2019-05-21 23:20:41 EDT,Photo,The @raptors even the Eastern Conference Final...,92,2
2,NaN,36984682,2019-05-21 21:18:51 EDT,Video,@sergeibaka keeps it alive for the @raptors! (...,60,3
3,NaN,36955156,2019-05-21 18:20:09 EDT,Video,???? The SUPERHUMAN HANDS of Giannis & Kawhi ?...,105,3
4,NaN,36955156,2019-05-21 15:04:31 EDT,Video,?? the @raptors & @bucks in transition! #NBABr...,121,3

In [7]:
data= data.rename(columns = {"Followers at Posting" : "NBA_Follower_Count"})

In [8]:
data['DayOfWeek']= pd.to_datetime(data['Created']).dt.day_name()

In [9]:
data.head()

,Engagements,NBA_Follower_Count,Created,Type,Description,Len_Desc,Tagged_Count,DayOfWeek
0,NaN,36984682,2019-05-22 00:31:55 EDT,Photo,The @raptors even up the Eastern Conference Fi...,55,1,Wednesday
1,NaN,36984682,2019-05-21 23:20:41 EDT,Photo,The @raptors even the Eastern Conference Final...,92,2,Tuesday
2,NaN,36984682,2019-05-21 21:18:51 EDT,Video,@sergeibaka keeps it alive for the @raptors! (...,60,3,Tuesday
3,NaN,36955156,2019-05-21 18:20:09 EDT,Video,???? The SUPERHUMAN HANDS of Giannis & Kawhi ?...,105,3,Tuesday
4,NaN,36955156,2019-05-21 15:04:31 EDT,Video,?? the @raptors & @bucks in transition! #NBABr...,121,3,Tuesday

In [10]:
data['Created']= pd.to_datetime(data['Created'])

In [11]:
def playoffDate(date): 
    if date > pd.Timestamp('2019-4-13'): 
        return 1 
    else: 
        return 0

In [12]:
data['playOffDate']= data.Created.map(lambda a: playoffDate(a.tz_localize(None)))

In [13]:
data['month'] = data.Created.map(lambda a: a.month)

In [14]:
data.head()

,Engagements,NBA_Follower_Count,Created,Type,Description,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month
0,NaN,36984682,2019-05-22 00:31:55-04:00,Photo,The @raptors even up the Eastern Conference Fi...,55,1,Wednesday,1,5
1,NaN,36984682,2019-05-21 23:20:41-04:00,Photo,The @raptors even the Eastern Conference Final...,92,2,Tuesday,1,5
2,NaN,36984682,2019-05-21 21:18:51-04:00,Video,@sergeibaka keeps it alive for the @raptors! (...,60,3,Tuesday,1,5
3,NaN,36955156,2019-05-21 18:20:09-04:00,Video,???? The SUPERHUMAN HANDS of Giannis & Kawhi ?...,105,3,Tuesday,1,5
4,NaN,36955156,2019-05-21 15:04:31-04:00,Video,?? the @raptors & @bucks in transition! #NBABr...,121,3,Tuesday,1,5

In [15]:
data['hour'] = data.Created.map(lambda a: a.hour)

In [16]:
data.head()

,Engagements,NBA_Follower_Count,Created,Type,Description,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month,hour
0,NaN,36984682,2019-05-22 00:31:55-04:00,Photo,The @raptors even up the Eastern Conference Fi...,55,1,Wednesday,1,5,0
1,NaN,36984682,2019-05-21 23:20:41-04:00,Photo,The @raptors even the Eastern Conference Final...,92,2,Tuesday,1,5,23
2,NaN,36984682,2019-05-21 21:18:51-04:00,Video,@sergeibaka keeps it alive for the @raptors! (...,60,3,Tuesday,1,5,21
3,NaN,36955156,2019-05-21 18:20:09-04:00,Video,???? The SUPERHUMAN HANDS of Giannis & Kawhi ?...,105,3,Tuesday,1,5,18
4,NaN,36955156,2019-05-21 15:04:31-04:00,Video,?? the @raptors & @bucks in transition! #NBABr...,121,3,Tuesday,1,5,15

In [17]:
def timeOfDay(hour): 
    if hour < 6: 
        return 'Night' 
    elif hour <12: 
        return 'Morning'
    elif hour <18: 
        return 'Afternoon'
    else:
        return'Evening'

In [18]:
data['timeOfDay']= data.hour.map(lambda a: timeOfDay(a))

In [19]:
data.head()

,Engagements,NBA_Follower_Count,Created,Type,Description,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month,hour,timeOfDay
0,NaN,36984682,2019-05-22 00:31:55-04:00,Photo,The @raptors even up the Eastern Conference Fi...,55,1,Wednesday,1,5,0,Night
1,NaN,36984682,2019-05-21 23:20:41-04:00,Photo,The @raptors even the Eastern Conference Final...,92,2,Tuesday,1,5,23,Evening
2,NaN,36984682,2019-05-21 21:18:51-04:00,Video,@sergeibaka keeps it alive for the @raptors! (...,60,3,Tuesday,1,5,21,Evening
3,NaN,36955156,2019-05-21 18:20:09-04:00,Video,???? The SUPERHUMAN HANDS of Giannis & Kawhi ?...,105,3,Tuesday,1,5,18,Evening
4,NaN,36955156,2019-05-21 15:04:31-04:00,Video,?? the @raptors & @bucks in transition! #NBABr...,121,3,Tuesday,1,5,15,Afternoon

In [20]:
def proportionOfTarget(caption): 
    #In this case target will be all non normal text
    targetCount = 0
    if not caption: return 0
    lst = caption.split(' ')
    count = len(lst)
    if count == 0: return 0
    for word in lst: 
        if len(word) ==0: continue 
        if word[0] in ['@', '#']: targetCount += 1
        elif '??' in word: targetCount+= 1
    return float(targetCount)/float(count)

In [21]:
data['propOfSpecialTexts'] = data.Description.map(lambda a: proportionOfTarget(a))

In [22]:
data.head()

,Engagements,NBA_Follower_Count,Created,Type,Description,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month,hour,timeOfDay,propOfSpecialTexts
0,NaN,36984682,2019-05-22 00:31:55-04:00,Photo,The @raptors even up the Eastern Conference Fi...,55,1,Wednesday,1,5,0,Night,0.111111
1,NaN,36984682,2019-05-21 23:20:41-04:00,Photo,The @raptors even the Eastern Conference Final...,92,2,Tuesday,1,5,23,Evening,0.133333
2,NaN,36984682,2019-05-21 21:18:51-04:00,Video,@sergeibaka keeps it alive for the @raptors! (...,60,3,Tuesday,1,5,21,Evening,0.444444
3,NaN,36955156,2019-05-21 18:20:09-04:00,Video,???? The SUPERHUMAN HANDS of Giannis & Kawhi ?...,105,3,Tuesday,1,5,18,Evening,0.375000
4,NaN,36955156,2019-05-21 15:04:31-04:00,Video,?? the @raptors & @bucks in transition! #NBABr...,121,3,Tuesday,1,5,15,Afternoon,0.375000

In [23]:
data['shoutouts']= data.Description.map(lambda x: re.findall('@\w*', x))
data.head()

,Engagements,NBA_Follower_Count,Created,Type,Description,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month,hour,timeOfDay,propOfSpecialTexts,shoutouts
0,NaN,36984682,2019-05-22 00:31:55-04:00,Photo,The @raptors even up the Eastern Conference Fi...,55,1,Wednesday,1,5,0,Night,0.111111,[@raptors]
1,NaN,36984682,2019-05-21 23:20:41-04:00,Photo,The @raptors even the Eastern Conference Final...,92,2,Tuesday,1,5,23,Evening,0.133333,"[@raptors, @bucks]"
2,NaN,36984682,2019-05-21 21:18:51-04:00,Video,@sergeibaka keeps it alive for the @raptors! (...,60,3,Tuesday,1,5,21,Evening,0.444444,"[@sergeibaka, @raptors, @nbaontnt]"
3,NaN,36955156,2019-05-21 18:20:09-04:00,Video,???? The SUPERHUMAN HANDS of Giannis & Kawhi ?...,105,3,Tuesday,1,5,18,Evening,0.375000,"[@bucks, @raptors, @nbaontnt]"
4,NaN,36955156,2019-05-21 15:04:31-04:00,Video,?? the @raptors & @bucks in transition! #NBABr...,121,3,Tuesday,1,5,15,Afternoon,0.375000,"[@raptors, @bucks, @nbaontnt]"

In [24]:
allVals = {}
for listItem in data['shoutouts']:
    for item in listItem:
        if item.lower() not in allVals: allVals[item.lower()] = 0
        allVals[item.lower()] = allVals[item.lower()] + 1

In [25]:
def tagLevel(tags):
    high = ['@kyrieirving', '@kingjames', '@stephencurry30', '@zo', '@easymoneysniper', '@spidadmitchell', '@jharden13', '@jaytatum0', '@dwyanewade', '@antdavis23', '@giannis_an34', '@karltowns', '@cp3', '@damianlillard', '@traeyoung', '@vicoladipo', '@lukadoncic', '@joelembiid', '@ygtrece']
    mid = ['@kevindurant', '@nbaontnt', '@lakers', '@demar_derozan', '@cavs', '@celtics' , '@nbatv', '@bensimmons', '@warriors', '@nyknicks', '@nbaonespn', '@timberwolves', '@atlhawks', '@russwest44', '@nbahistory', '@suns', '@washwizards', '@laclippers', '@hornets', '@pacers', '@miamiheat', '@houstonrockets', '@sacramentokings']
    low = ['@dallasmavs', '@sixers', '@bucks', '@raptors', '@trailblazers', '@orlandomagic', '@utahjazz', '@nbaallstar', '@pelicansnba', '@spurs', '@detroitpistons', '@brooklynnets', '@okcthunder', '@nuggets', '@nbasummerleague']
    
    if set(tags).intersection(set(high)):
        return 'High'
    elif set(tags).intersection(set(mid)):
        return 'Mid'
    elif set(tags).intersection(set(low)):
        return 'Low'
    else:
        return 'None'

In [26]:
data['TagLevel'] = data.shoutouts.map(lambda a: tagLevel(a))
data.head()

,Engagements,NBA_Follower_Count,Created,Type,Description,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month,hour,timeOfDay,propOfSpecialTexts,shoutouts,TagLevel
0,NaN,36984682,2019-05-22 00:31:55-04:00,Photo,The @raptors even up the Eastern Conference Fi...,55,1,Wednesday,1,5,0,Night,0.111111,[@raptors],Low
1,NaN,36984682,2019-05-21 23:20:41-04:00,Photo,The @raptors even the Eastern Conference Final...,92,2,Tuesday,1,5,23,Evening,0.133333,"[@raptors, @bucks]",Low
2,NaN,36984682,2019-05-21 21:18:51-04:00,Video,@sergeibaka keeps it alive for the @raptors! (...,60,3,Tuesday,1,5,21,Evening,0.444444,"[@sergeibaka, @raptors, @nbaontnt]",Mid
3,NaN,36955156,2019-05-21 18:20:09-04:00,Video,???? The SUPERHUMAN HANDS of Giannis & Kawhi ?...,105,3,Tuesday,1,5,18,Evening,0.375000,"[@bucks, @raptors, @nbaontnt]",Mid
4,NaN,36955156,2019-05-21 15:04:31-04:00,Video,?? the @raptors & @bucks in transition! #NBABr...,121,3,Tuesday,1,5,15,Afternoon,0.375000,"[@raptors, @bucks, @nbaontnt]",Mid

In [27]:
teams = ['@nuggets ','@spurs ', '@okcthunder ', '@pelicansnba ','@dallasmavs ', '@trailblazers ', '@utahjazz ',
        '@bucks ', '@sixers ','@raptors ','@laclippers ', '@miamiheat ', '@pacers ', '@houstonrockets ',
        '@timberwolves ', '@cavs ', '@warriors ','@celtics ','@lakers ','@sacramentokings ', '@orlandomagic ', '@detroitpistons ',
         '@brooklynnets ','@atlhawks ', '@memgrizz ', '@suns ', '@hornets ', '@washwizards ', '@nyknicks ', '@chicagobulls '
        ]

In [28]:
def teamTagged(lst): 
    for tag in lst: 
        if tag in teams: 
            return 1 
    return 0

In [29]:
data['teamTagged']= data.shoutouts.map(lambda a: teamTagged(a))

In [30]:
data.head()

,Engagements,NBA_Follower_Count,Created,Type,Description,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month,hour,timeOfDay,propOfSpecialTexts,shoutouts,TagLevel,teamTagged
0,NaN,36984682,2019-05-22 00:31:55-04:00,Photo,The @raptors even up the Eastern Conference Fi...,55,1,Wednesday,1,5,0,Night,0.111111,[@raptors],Low,0
1,NaN,36984682,2019-05-21 23:20:41-04:00,Photo,The @raptors even the Eastern Conference Final...,92,2,Tuesday,1,5,23,Evening,0.133333,"[@raptors, @bucks]",Low,0
2,NaN,36984682,2019-05-21 21:18:51-04:00,Video,@sergeibaka keeps it alive for the @raptors! (...,60,3,Tuesday,1,5,21,Evening,0.444444,"[@sergeibaka, @raptors, @nbaontnt]",Mid,0
3,NaN,36955156,2019-05-21 18:20:09-04:00,Video,???? The SUPERHUMAN HANDS of Giannis & Kawhi ?...,105,3,Tuesday,1,5,18,Evening,0.375000,"[@bucks, @raptors, @nbaontnt]",Mid,0
4,NaN,36955156,2019-05-21 15:04:31-04:00,Video,?? the @raptors & @bucks in transition! #NBABr...,121,3,Tuesday,1,5,15,Afternoon,0.375000,"[@raptors, @bucks, @nbaontnt]",Mid,0

In [31]:
def otherTagged(lst): 
    for tag in lst: 
        if tag not in teams: 
            return 1 
    return 0 

data['otherTagged']= data.shoutouts.map(lambda a: otherTagged(a))

In [32]:
top3 = ['@kyrieirving ','@kingjames ', '@stephencurry30 ']
bottom3 = ['@nuggets ','@spurs ','@okcthunder ' ]

def top3Tagged(lst): 
    for tag in lst: 
        if tag in top3: 
            return 1 
    return 0 

data['top3Tagged']= data.shoutouts.map(lambda a: top3Tagged(a))

def bottom3Tagged(lst): 
    for tag in lst: 
        if tag in bottom3: 
            return 1 
    return 0 

data['bottom3Tagged']= data.shoutouts.map(lambda a: bottom3Tagged(a))

In [33]:
data['hashtags']= data.Description.map(lambda x: re.findall('#\w*', x))
data.head()

,Engagements,NBA_Follower_Count,Created,Type,Description,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month,hour,timeOfDay,propOfSpecialTexts,shoutouts,TagLevel,teamTagged,otherTagged,top3Tagged,bottom3Tagged,hashtags
0,NaN,36984682,2019-05-22 00:31:55-04:00,Photo,The @raptors even up the Eastern Conference Fi...,55,1,Wednesday,1,5,0,Night,0.111111,[@raptors],Low,0,1,0,0,[]
1,NaN,36984682,2019-05-21 23:20:41-04:00,Photo,The @raptors even the Eastern Conference Final...,92,2,Tuesday,1,5,23,Evening,0.133333,"[@raptors, @bucks]",Low,0,1,0,0,[]
2,NaN,36984682,2019-05-21 21:18:51-04:00,Video,@sergeibaka keeps it alive for the @raptors! (...,60,3,Tuesday,1,5,21,Evening,0.444444,"[@sergeibaka, @raptors, @nbaontnt]",Mid,0,1,0,0,[]
3,NaN,36955156,2019-05-21 18:20:09-04:00,Video,???? The SUPERHUMAN HANDS of Giannis & Kawhi ?...,105,3,Tuesday,1,5,18,Evening,0.375000,"[@bucks, @raptors, @nbaontnt]",Mid,0,1,0,0,[]
4,NaN,36955156,2019-05-21 15:04:31-04:00,Video,?? the @raptors & @bucks in transition! #NBABr...,121,3,Tuesday,1,5,15,Afternoon,0.375000,"[@raptors, @bucks, @nbaontnt]",Mid,0,1,0,0,[#NBABreakdown]

In [34]:
data['hasHashtag']=data.hashtags.map(lambda x: x != [])

In [35]:
def HashLevel(hashs):
    high = ['#KiaTipOff18', '#NBAPreseason', '#OneLastDance', '#NBAonABC', '#KiaTipOff17', '#BESTofNBA', '#nbapreseason', '#PhantomCam', '#NBABreakdown']
    mid = ['#NBAChinaGames', '#NBAFinals', '#NBAPlayoffs', '#NBAAllStar', '#NBAXmas', '#ThisIsYourTime', '#ThisIsWhyWePlay']
    low = ['#NBAKicks', '#TripleDoubleAlert', '#NBADraft', '#NBABDAY', '#NBAAwards', '#NBARooks', '#NBAMediaDay', '#TissotBuzzerBeater', '#NBASummer']
    
    if set(hashs).intersection(set(high)):
        return 'High'
    elif set(hashs).intersection(set(mid)):
        return 'Mid'
    elif set(hashs).intersection(set(low)):
        return 'Low'
    else:
        return 'None'

In [36]:
data['HashLevel'] = data.hashtags.map(lambda a: HashLevel(a))
data.head()

,Engagements,NBA_Follower_Count,Created,Type,Description,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month,...,propOfSpecialTexts,shoutouts,TagLevel,teamTagged,otherTagged,top3Tagged,bottom3Tagged,hashtags,hasHashtag,HashLevel
0,NaN,36984682,2019-05-22 00:31:55-04:00,Photo,The @raptors even up the Eastern Conference Fi...,55,1,Wednesday,1,5,...,0.111111,[@raptors],Low,0,1,0,0,[],False,None
1,NaN,36984682,2019-05-21 23:20:41-04:00,Photo,The @raptors even the Eastern Conference Final...,92,2,Tuesday,1,5,...,0.133333,"[@raptors, @bucks]",Low,0,1,0,0,[],False,None
2,NaN,36984682,2019-05-21 21:18:51-04:00,Video,@sergeibaka keeps it alive for the @raptors! (...,60,3,Tuesday,1,5,...,0.444444,"[@sergeibaka, @raptors, @nbaontnt]",Mid,0,1,0,0,[],False,None
3,NaN,36955156,2019-05-21 18:20:09-04:00,Video,???? The SUPERHUMAN HANDS of Giannis & Kawhi ?...,105,3,Tuesday,1,5,...,0.375000,"[@bucks, @raptors, @nbaontnt]",Mid,0,1,0,0,[],False,None
4,NaN,36955156,2019-05-21 15:04:31-04:00,Video,?? the @raptors & @bucks in transition! #NBABr...,121,3,Tuesday,1,5,...,0.375000,"[@raptors, @bucks, @nbaontnt]",Mid,0,1,0,0,[#NBABreakdown],True,High

In [37]:
data['monthDateYear']= data.Created.map(lambda x: x.strftime('%Y-%m-%d'))

In [38]:
x =data.groupby(['monthDateYear']).size()
x= x.reset_index()
data = data.merge(x, left_on='monthDateYear', right_on='monthDateYear')
data = data.rename(columns={0: 'postsInThatDay'})

In [39]:
data.head()

,Engagements,NBA_Follower_Count,Created,Type,Description,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month,...,TagLevel,teamTagged,otherTagged,top3Tagged,bottom3Tagged,hashtags,hasHashtag,HashLevel,monthDateYear,postsInThatDay
0,NaN,36984682,2019-05-22 00:31:55-04:00,Photo,The @raptors even up the Eastern Conference Fi...,55,1,Wednesday,1,5,...,Low,0,1,0,0,[],False,None,2019-05-22,1
1,NaN,36984682,2019-05-21 23:20:41-04:00,Photo,The @raptors even the Eastern Conference Final...,92,2,Tuesday,1,5,...,Low,0,1,0,0,[],False,None,2019-05-21,6
2,NaN,36984682,2019-05-21 21:18:51-04:00,Video,@sergeibaka keeps it alive for the @raptors! (...,60,3,Tuesday,1,5,...,Mid,0,1,0,0,[],False,None,2019-05-21,6
3,NaN,36955156,2019-05-21 18:20:09-04:00,Video,???? The SUPERHUMAN HANDS of Giannis & Kawhi ?...,105,3,Tuesday,1,5,...,Mid,0,1,0,0,[],False,None,2019-05-21,6
4,NaN,36955156,2019-05-21 15:04:31-04:00,Video,?? the @raptors & @bucks in transition! #NBABr...,121,3,Tuesday,1,5,...,Mid,0,1,0,0,[#NBABreakdown],True,High,2019-05-21,6

In [40]:
data.to_csv('tesketit2.csv', index=False)