In [1]:
import pandas as pd
import datetime
import numpy as np
import sklearn as sk

In [2]:
data = pd.read_csv('Data_For_Modeling/esketit.csv', encoding = "ISO-8859-1")

In [3]:
data.head()

,Engagements,NBA_Follower_Count,Created,Type,Description,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month,...,timeOfDay,propOfSpecialTexts,shoutouts,teamTagged,otherTagged,top3Tagged,bottom3Tagged,hashtags,monthDateYear,postsInThatDay
0,502093,36984682,2019-05-22 03:30:51,Video,The @raptors bench trio of @sergeibaka @norman...,95,4,Wednesday,1,5,...,Night,0.266667,"['@raptors ', '@sergeibaka ', '@normanpowell4 ...",1,1,0,0,[],2019-05-22,5
1,603380,36984682,2019-05-22 02:53:33,Video,@kyle_lowry7 pulls from deep for the @raptors ...,64,2,Wednesday,1,5,...,Night,0.166667,"['@kyle_lowry7 ', '@raptors ']",1,1,0,0,[],2019-05-22,5
2,603380,36984682,2019-05-22 02:19:58,Video,@k_mid22 with some english on the @bucks dime!,46,2,Wednesday,1,5,...,Night,0.250000,"['@k_mid22 ', '@bucks ']",1,1,0,0,[],2019-05-22,5
3,725100,36984682,2019-05-22 02:02:41,Video,Kawhi punches it home with the left on TNT!,43,0,Wednesday,1,5,...,Night,0.000000,[],0,0,0,0,[],2019-05-22,5
4,661446,36984682,2019-05-22 00:47:49,Video,@giannis_an34 goes baseline early to rock the ...,57,1,Wednesday,1,5,...,Night,0.100000,['@giannis_an34 '],0,1,0,0,[],2019-05-22,5

In [5]:
x= pd.get_dummies(data['Type'])
x['Not_Video'] = x['Album']+x['Photo']
x.head()

   Album  Photo  Video  Not_Video
0      0      0      1          0
1      0      0      1          0
2      0      0      1          0
3      0      0      1          0
4      0      0      1          0

In [9]:
data.join(x.drop(['Album','Photo'],axis = 1))

,Engagements,NBA_Follower_Count,Created,Type,Description,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month,...,shoutouts,teamTagged,otherTagged,top3Tagged,bottom3Tagged,hashtags,monthDateYear,postsInThatDay,Video,Not_Video
0,502093,36984682,2019-05-22 03:30:51,Video,The @raptors bench trio of @sergeibaka @norman...,95,4,Wednesday,1,5,...,"['@raptors ', '@sergeibaka ', '@normanpowell4 ...",1,1,0,0,[],2019-05-22,5,1,0
1,603380,36984682,2019-05-22 02:53:33,Video,@kyle_lowry7 pulls from deep for the @raptors ...,64,2,Wednesday,1,5,...,"['@kyle_lowry7 ', '@raptors ']",1,1,0,0,[],2019-05-22,5,1,0
2,603380,36984682,2019-05-22 02:19:58,Video,@k_mid22 with some english on the @bucks dime!,46,2,Wednesday,1,5,...,"['@k_mid22 ', '@bucks ']",1,1,0,0,[],2019-05-22,5,1,0
3,725100,36984682,2019-05-22 02:02:41,Video,Kawhi punches it home with the left on TNT!,43,0,Wednesday,1,5,...,[],0,0,0,0,[],2019-05-22,5,1,0
4,661446,36984682,2019-05-22 00:47:49,Video,@giannis_an34 goes baseline early to rock the ...,57,1,Wednesday,1,5,...,['@giannis_an34 '],0,1,0,0,[],2019-05-22,5,1,0
5,322444,36955156,2019-05-21 18:02:32,Photo,Congrats to the 2018-19 NBA All-Rookie First T...,104,2,Tuesday,1,5,...,['@lukadoncic '],0,1,0,0,[],2019-05-21,19,0,1
6,722540,36955156,2019-05-21 16:30:53,Video,The @warriors locked in for four games to adva...,106,1,Tuesday,1,5,...,['@warriors '],1,0,0,0,['#NBAFinals '],2019-05-21,19,1,0
7,339265,36955156,2019-05-21 12:59:02,Photo,Will the @bucks take a commanding 3-1 lead... ...,88,2,Tuesday,1,5,...,"['@bucks ', '@raptors ']",1,0,0,0,[],2019-05-21,19,0,1
8,443330,36955156,2019-05-21 04:48:16,Photo,TAP to SHOP the @warriors Western Conference C...,75,2,Tuesday,1,5,...,['@warriors '],1,0,0,0,[],2019-05-21,19,0,1
9,652193,36955156,2019-05-21 04:38:18,Video,Hey @stephencurry30... that was the first time...,121,2,Tuesday,1,5,...,[],0,0,0,0,['#NBAPlayoffs '],2019-05-21,19,1,0
10,652193,36955156,2019-05-21 04:31:13,Video,@stephencurry30 (37/13/11) & @money23green (18...,148,2,Tuesday,1,5,...,"['@stephencurry30 ', '@money23green ']",0,1,1,0,['#NBAPlayoffs '],2019-05-21,19,1,0
11,443330,36955156,2019-05-21 04:24:13,Photo,The @warriors defeat @trailblazers 119-117 to ...,114,2,Tuesday,1,5,...,"['@warriors ', '@trailblazers ']",1,0,0,0,['#NBAFinals '],2019-05-21,19,0,1
12,713427,36955156,2019-05-21 04:21:06,Video,@money23green (18/14/11) reacts to a 5th strai...,91,2,Tuesday,1,5,...,['@money23green '],0,1,0,0,['#NBAFinals '],2019-05-21,19,1,0
13,470233,36955156,2019-05-21 03:54:39,Photo,The @warriors win the West & advance to their ...,97,1,Tuesday,1,5,...,['@warriors '],1,0,0,0,['#NBAFinals '],2019-05-21,19,0,1
14,675091,36955156,2019-05-21 03:45:36,Video,@money23green triple extends the @warriors lea...,80,2,Tuesday,1,5,...,"['@money23green ', '@warriors ']",1,1,0,0,[],2019-05-21,19,1,0
15,443543,36955156,2019-05-21 03:33:24,Photo,@stephencurry30 & @money23green become the fir...,129,3,Tuesday,1,5,...,"['@stephencurry30 ', '@money23green ', '@nbahi...",0,1,1,0,['#NBAPlayoffs '],2019-05-21,19,0,1
16,718485,36955156,2019-05-21 03:29:25,Video,?? @meyersleonard11! ?? (??: ESPN),34,1,Tuesday,1,5,...,[],0,0,0,0,[],2019-05-21,19,1,0
17,427347,36955156,2019-05-21 03:27:54,Photo,@money23green notches the triple-double for th...,102,2,Tuesday,1,5,...,"['@money23green ', '@warriors ']",1,1,0,0,[],2019-05-21,19,0,1
18,696779,36955156,2019-05-21 03:24:11,Video,@stephencurry30 dime & hesi in the 4th on ESPN...,60,1,Tuesday,1,5,...,['@stephencurry30 '],0,1,1,0,[],2019-05-21,19,1,0
19,569271,36955156,2019-05-21 03:22:01,Photo,@stephencurry30 notches the triple-double for ...,104,2,Tuesday,1,5,...,"['@stephencurry30 ', '@warriors ']",1,1,1,0,[],2019-05-21,19,0,1
20,603391,36955156,2019-05-21 02:40:42,Video,@damianlillard uses his dribble into the @trai...,62,2,Tuesday,1,5,...,"['@damianlillard ', '@trailblazers ']",1,1,0,0,[],2019-05-21,19,1,0
21,603391,36955156,2019-05-21 02:33:01,Video,@meyersleonard11 puts up 25 in the first half ...,76,2,Tuesday,1,5,...,"['@meyersleonard11 ', '@trailblazers ']",1,1,0,0,[],2019-05-21,19,1,0
22,711819,36955156,2019-05-21 01:26:13,Video,@stephencurry30 tosses it up early on ESPN!,43,1,Tuesday,1,5,...,['@stephencurry30 '],0,1,1,0,[],2019-05-21,19,1,0
23,404760,36955156,2019-05-21 00:31:46,Photo,@money23green arrives for Game 4 of the Wester...,114,1,Tuesday,1,5,...,['@money23green '],0,1,0,0,['#PowerbeatsPro '],2019-05-21,19,0,1
24,534517,36928789,2019-05-20 21:54:34,Video,In @budweiserusa #LegendaryMoments history.. w...,208,4,Monday,1,5,...,"['@budweiserusa ', '@trailblazers ', '@trailbl...",1,1,0,0,['#LegendaryMoments '],2019-05-20,15,1,0
25,590945,36928789,2019-05-20 16:05:19,Video,@money23green showcases his ?? IQ on both ends...,139,4,Monday,1,5,...,"['@money23green ', '@warriors ', '@trailblazer...",1,1,0,0,[],2019-05-20,15,1,0
26,354472,36928789,2019-05-20 14:07:04,Photo,ItÃ‚Â’s WIN or Go Home for the @trailblazers... ...,102,3,Monday,1,5,...,['@warriors '],1,0,0,0,[],2019-05-20,15,0,1
27,412221,36928789,2019-05-20 04:45:16,Photo,The @raptors get on the board at home in the E...,71,1,Monday,1,5,...,['@raptors '],1,0,0,0,[],2019-05-20,15,0,1
28,646075,36928789,2019-05-20 03:09:33,Video,Kawhi on tonightÃ‚Â’s gritty @raptors 2OT win wi...,63,2,Monday,1,5,...,['@raptors '],1,0,0,0,[],2019-05-20,15,1,0
29,708249,36928789,2019-05-20 02:49:10,Video,Kawhi Leonard scores 19 of his game-high 36 in...,111,1,Monday,1,5,...,['@raptors '],1,0,0,0,[],2019-05-20,15,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7736,372879,24893189,2017-10-04 02:20:37,Photo,Just like at home growing up... Justin x Jrue!...,60,0,Wednesday,0,10,...,[],0,0,0,0,[],2017-10-04,15,0,1
7737,372879,24893189,2017-10-04 02:17:08,Album,Back in action! #NBAPreseason,29,0,Wednesday,0,10,...,[],0,0,0,0,[],2017-10-04,15,0,1
7738,664655,24893189,2017-10-04 01:27:43,Video,@cp3 notches his first dime and points for the...,77,2,Wednesday,0,10,...,['@cp3 '],0,1,0,0,[],2017-10-04,15,1,0
7739,716117,24893189,2017-10-04 01:14:42,Video,?? @kporzee off the dribble for the @nyknicks!,46,2,Wednesday,0,10,...,['@kporzee '],0,1,0,0,[],2017-10-04,15,1,0
7740,606308,24893189,2017-10-04 00:54:40,Video,@carmeloanthony & @ygtrece get on the board fo...,78,3,Wednesday,0,10,...,"['@carmeloanthony ', '@ygtrece ']",0,1,0,0,[],2017-10-04,15,1,0
7741,372879,24893189,2017-10-03 22:58:31,Photo,They got NEXT. #NBARooks,24,0,Tuesday,0,10,...,[],0,0,0,0,[],2017-10-03,14,0,1
7742,294008,24893189,2017-10-03 20:13:56,Photo,TonightÃ‚Â’s #NBAPreseason on @nbatv tripleheader!!,48,1,Tuesday,0,10,...,['@nbatv '],0,1,0,0,['#NBAPreseason '],2017-10-03,14,0,1
7743,614033,24893189,2017-10-03 17:19:29,Video,@realtristan13 signs off from todayÃ‚Â’s @cavs p...,68,2,Tuesday,0,10,...,"['@realtristan13 ', '@cavs ']",1,1,0,0,[],2017-10-03,14,1,0
7744,368624,24893189,2017-10-03 16:10:42,Photo,???? @isaiahthomas ???? #CavsAllAccess,38,1,Tuesday,0,10,...,['@isaiahthomas '],0,1,0,0,[],2017-10-03,14,0,1
7745,685118,24893189,2017-10-03 15:45:03,Video,The @cavs get loose... #CavsAllAccess,37,1,Tuesday,0,10,...,['@cavs '],1,0,0,0,[],2017-10-03,14,1,0
7746,768903,24893189,2017-10-03 14:37:41,Video,@kingjames & @dwyanewade gets shots up ahead o...,86,3,Tuesday,0,10,...,"['@kingjames ', '@dwyanewade ', '@cavs ']",1,1,1,0,[],2017-10-03,14,1,0
7747,341154,24893189,2017-10-03 13:38:29,Album,Early in the gym with @kingjames & @dwyanewade...,93,2,Tuesday,0,10,...,"['@kingjames ', '@dwyanewade ']",0,1,1,0,[],2017-10-03,14,0,1
7748,681995,24893189,2017-10-03 05:22:22,Video,@kuzmakyle puts up 23 in his second #NBAPresea...,77,2,Tuesday,0,10,...,"['@kuzmakyle ', '@lakers ']",1,1,0,0,['#NBAPreseason '],2017-10-03,14,1,0
7749,826258,24893189,2017-10-03 05:03:20,Video,My first bucket! #NBAPreseason #ThisIsWhyWePlay,47,0,Tuesday,0,10,...,[],0,0,0,0,['#NBAPreseason '],2017-10-03,14,1,0
7750,721972,24885537,2017-10-03 03:40:10,Video,@jordanclarksons ?? @zo ?? #NBAPreseason,40,2,Tuesday,0,10,...,"['@jordanclarksons ', '@zo ']",0,1,0,0,[],2017-10-03,14,1,0
7751,606319,24885537,2017-10-03 03:13:38,Video,New @utahjazz teammates @ruuufio & @rudygobert...,71,3,Tuesday,0,10,...,"['@utahjazz ', '@ruuufio ', '@rudygobert27 ']",1,1,0,0,[],2017-10-03,14,1,0
7752,728631,24885537,2017-10-03 01:08:23,Video,@desmith4 got hops! #NBAPreseason,33,1,Tuesday,0,10,...,['@desmith4 '],0,1,0,0,[],2017-10-03,14,1,0
7753,373499,24885537,2017-10-03 00:20:36,Photo,????,4,0,Tuesday,0,10,...,[],0,0,0,0,[],2017-10-03,14,0,1
7754,972546,24885537,2017-10-03 00:13:01,Video,@kyrieirving shows off the bounce for Boston! ...,59,1,Tuesday,0,10,...,['@kyrieirving '],0,1,1,0,[],2017-10-03,14,1,0
7755,738244,24885537,2017-10-02 23:50:44,Video,@gdhayward and @kyrieirving are introduced in ...,107,4,Monday,0,10,...,"['@gdhayward ', '@kyrieirving ', '@celtics ', ...",1,1,1,0,['#NBAPreseason '],2017-10-02,6,1,0
7756,769381,24885537,2017-10-02 19:31:46,Video,The @warriors have arrived in Shenzhen for the...,67,1,Monday,0,10,...,['@warriors '],1,0,0,0,[],2017-10-02,6,1,0
7757,318910,24885537,2017-10-02 17:19:09,Photo,NaN,0,0,Monday,0,10,...,[],0,0,0,0,[],2017-10-02,6,0,1
7758,622136,24885537,2017-10-02 05:07:31,Video,@kyle_lowry7 and @demar_derozan combine for 28...,75,3,Monday,0,10,...,"['@kyle_lowry7 ', '@demar_derozan ', '@raptors ']",1,1,0,0,['#NBAPreseason '],2017-10-02,6,1,0
7759,333744,24875542,2017-10-02 03:01:06,Photo,The @minnesotalynx force a Winner Takes All Ga...,76,1,Monday,0,10,...,['@minnesotalynx '],0,1,0,0,[],2017-10-02,6,0,1
7760,649210,24875542,2017-10-02 02:30:08,Video,New @laclippers connect as @milosteodosic4 fee...,85,3,Monday,0,10,...,"['@laclippers ', '@milosteodosic4 ']",1,1,0,0,[],2017-10-02,6,1,0
7761,891723,24875542,2017-10-01 23:38:26,Video,16 days from #KiaTipOff17... we showcase the @...,79,1,Sunday,0,10,...,['@warriors '],1,0,0,0,[],2017-10-01,5,1,0
7762,599763,24875542,2017-10-01 17:31:04,Video,The @minnesotalynx look to force a Game 5... w...,126,3,Sunday,0,10,...,"['@minnesotalynx ', '@la_sparks ', '@wnba ']",0,1,0,0,[],2017-10-01,5,1,0
7763,233101,24875542,2017-10-01 13:38:35,Album,ItÃ‚Â’s OCTOBER and ?? is back! \n#NBAPreseason,43,0,Sunday,0,10,...,[],0,0,0,0,[],2017-10-01,5,0,1
7764,607667,24875542,2017-10-01 06:13:54,Video,"The newest @timberwolves.... @jimmybutler, @je...",103,4,Sunday,0,10,...,"['@jeffteague ', '@tajgibson22 ']",0,1,0,0,['#NBAPreseason '],2017-10-01,5,1,0
7765,730252,24875542,2017-10-01 04:54:29,Video,"@zo puts up 8 assists, 7 rebounds & 5 points i...",80,2,Sunday,0,10,...,"['@zo ', '@lakers ']",1,1,0,0,['#NBAPreseason '],2017-10-01,5,1,0

In [11]:
data.columns

Index(['Engagements', 'NBA_Follower_Count', 'Created', 'Type', 'Description',
       'Len_Desc', 'Tagged_Count', 'DayOfWeek', 'playOffDate', 'month', 'hour',
       'timeOfDay', 'propOfSpecialTexts', 'shoutouts', 'teamTagged',
       'otherTagged', 'top3Tagged', 'bottom3Tagged', 'hashtags',
       'monthDateYear', 'postsInThatDay'],
      dtype='object')

In [13]:
data= data.drop(['shoutouts','hashtags','monthDateYear','Created','Type','Description'],axis = 1)

In [14]:
data.head()

,Engagements,NBA_Follower_Count,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month,hour,timeOfDay,propOfSpecialTexts,teamTagged,otherTagged,top3Tagged,bottom3Tagged,postsInThatDay
0,502093,36984682,95,4,Wednesday,1,5,3,Night,0.266667,1,1,0,0,5
1,603380,36984682,64,2,Wednesday,1,5,2,Night,0.166667,1,1,0,0,5
2,603380,36984682,46,2,Wednesday,1,5,2,Night,0.250000,1,1,0,0,5
3,725100,36984682,43,0,Wednesday,1,5,2,Night,0.000000,0,0,0,0,5
4,661446,36984682,57,1,Wednesday,1,5,0,Night,0.100000,0,1,0,0,5

In [18]:
data = data.join(pd.get_dummies(data['timeOfDay']))

In [19]:
data = data.join(pd.get_dummies(data['DayOfWeek']))

In [20]:
data.head()

,Engagements,NBA_Follower_Count,Len_Desc,Tagged_Count,DayOfWeek,playOffDate,month,hour,timeOfDay,propOfSpecialTexts,...,Evening,Morning,Night,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,502093,36984682,95,4,Wednesday,1,5,3,Night,0.266667,...,0,0,1,0,0,0,0,0,0,1
1,603380,36984682,64,2,Wednesday,1,5,2,Night,0.166667,...,0,0,1,0,0,0,0,0,0,1
2,603380,36984682,46,2,Wednesday,1,5,2,Night,0.250000,...,0,0,1,0,0,0,0,0,0,1
3,725100,36984682,43,0,Wednesday,1,5,2,Night,0.000000,...,0,0,1,0,0,0,0,0,0,1
4,661446,36984682,57,1,Wednesday,1,5,0,Night,0.100000,...,0,0,1,0,0,0,0,0,0,1

In [21]:
data= data.drop(['DayOfWeek','timeOfDay'],axis = 1)

In [22]:
data.head()

,Engagements,NBA_Follower_Count,Len_Desc,Tagged_Count,playOffDate,month,hour,propOfSpecialTexts,teamTagged,otherTagged,...,Evening,Morning,Night,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,502093,36984682,95,4,1,5,3,0.266667,1,1,...,0,0,1,0,0,0,0,0,0,1
1,603380,36984682,64,2,1,5,2,0.166667,1,1,...,0,0,1,0,0,0,0,0,0,1
2,603380,36984682,46,2,1,5,2,0.250000,1,1,...,0,0,1,0,0,0,0,0,0,1
3,725100,36984682,43,0,1,5,2,0.000000,0,0,...,0,0,1,0,0,0,0,0,0,1
4,661446,36984682,57,1,1,5,0,0.100000,0,1,...,0,0,1,0,0,0,0,0,0,1

In [24]:
data.columns

Index(['Engagements', 'NBA_Follower_Count', 'Len_Desc', 'Tagged_Count',
       'playOffDate', 'month', 'hour', 'propOfSpecialTexts', 'teamTagged',
       'otherTagged', 'top3Tagged', 'bottom3Tagged', 'postsInThatDay',
       'Afternoon', 'Evening', 'Morning', 'Night', 'Friday', 'Monday',
       'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday'],
      dtype='object')

In [29]:
test = data[['NBA_Follower_Count', 'Len_Desc', 'Tagged_Count',
       'playOffDate', 'month', 'hour', 'propOfSpecialTexts']]

In [28]:
from sklearn import preprocessing, svm

In [30]:
X = preprocessing.scale(test)

In [36]:
Y = pd.DataFrame(X).rename(columns={0:'NBA_Follower_Count', 1:'Len_Desc', 2:'Tagged_Count',
       3:'playOffDate', 4:'month', 5:'hour', 6:'propOfSpecialTexts'})

In [37]:
Z = data[['teamTagged',
       'otherTagged', 'top3Tagged', 'bottom3Tagged', 'postsInThatDay',
       'Afternoon', 'Evening', 'Morning', 'Night', 'Friday', 'Monday',
       'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday']]

In [41]:
processedData= Y.join(Z).drop('hour', axis =1)

In [42]:
processedData.head()

,NBA_Follower_Count,Len_Desc,Tagged_Count,playOffDate,month,propOfSpecialTexts,teamTagged,otherTagged,top3Tagged,bottom3Tagged,...,Evening,Morning,Night,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,1.749128,0.698583,2.216012,3.459038,-0.25383,0.003876,1,1,0,0,...,0,0,1,0,0,0,0,0,0,1
1,1.749128,-0.136075,0.436787,3.459038,-0.25383,-0.543573,1,1,0,0,...,0,0,1,0,0,0,0,0,0,1
2,1.749128,-0.620715,0.436787,3.459038,-0.25383,-0.087365,1,1,0,0,...,0,0,1,0,0,0,0,0,0,1
3,1.749128,-0.701488,-1.342437,3.459038,-0.25383,-1.455990,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
4,1.749128,-0.324546,-0.452825,3.459038,-0.25383,-0.908540,0,1,0,0,...,0,0,1,0,0,0,0,0,0,1

In [43]:
target = data['Engagements']

In [45]:
from sklearn.model_selection import train_test_split

In [54]:
from sklearn.feature_selection import SelectKBest, f_regression

In [46]:
X_train, X_test, y_train, y_test = train_test_split(processedData, target, test_size=0.2)

In [47]:
X_train.head()

,NBA_Follower_Count,Len_Desc,Tagged_Count,playOffDate,month,propOfSpecialTexts,teamTagged,otherTagged,top3Tagged,bottom3Tagged,...,Evening,Morning,Night,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
5864,-0.927559,0.267792,0.436787,-0.289098,-1.021449,0.733810,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
824,1.398542,1.263996,0.436787,-0.289098,-0.765576,-0.908540,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4230,-0.355206,0.483187,0.436787,-0.289098,0.002043,0.825051,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
2914,0.468790,-0.136075,1.326400,-0.289098,1.281407,0.596947,1,1,0,0,...,0,0,1,1,0,0,0,0,0,0
3322,0.272982,0.267792,0.436787,-0.289098,1.025534,-0.192644,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [59]:
X_new_train

array([[ 0.26779181,  0.43678741, -0.28909775, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.26399632,  0.43678741, -0.28909775, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.48318738,  0.43678741, -0.28909775, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [-0.86303494, -0.45282471, -0.28909775, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.05239623,  0.43678741, -0.28909775, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.61780961, -0.45282471, -0.28909775, ...,  0.        ,
         0.        ,  0.        ]])

In [60]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR

In [62]:
parameters = [{'kernel':['rbf','linear','poly','sigmoid'],
               'gamma':[1e-2,1e-3,1e-4,1e-5],
               'C':[0.01,0.1,1,10]}]

# used grid search to find optimal kernel, gamma, C
gs = GridSearchCV(SVR(), parameters, cv=5, verbose=1)
gs.fit(X_train, y_train)
svm = gs.best_estimator_

# builds forecast column of df
forecast_set = svm.predict(X_test)

# MAPE
def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

print ('svm mape:', mean_absolute_percentage_error(y_test, forecast_set))

Fitting 5 folds for each of 64 candidates, totalling 320 fits

[Parallel(n_jobs=1)]: Done 320 out of 320 | elapsed:  5.9min finished

ValueError: X.shape[1] = 22 should be equal to 10, the number of features at training time